import type { GravityCoreStatus, GravityModule, GravityModelProvider } from "@gravity/contracts"

export const gravCoreModules: GravityModule[] = [
  {
    id: "assistant",
    name: "Grav Assistant",
    description: "Conversation contract and operator-facing assistant surface.",
    sourcePath: "services/grav-core/src/ollama.ts",
    connectionState: "connected",
    capabilities: [
      { id: "assistant.chat", title: "Assistant chat", description: "Route user messages through Core orchestration before provider execution.", status: "connected" },
      { id: "assistant.chat.audit", title: "Chat audit events", description: "Record redacted audit events for Core chat attempts.", status: "connected" },
      { id: "assistant.chat.memory", title: "MemPalace-aware chat", description: "Retrieve relevant snippets from modules/memory MemPalace and inject them into provider context.", status: "connected" },
      { id: "assistant.tools", title: "Module skill/tool access", description: "Expose connected module capabilities through Core /skills, /tools, and /tools/run.", status: "connected" },
    ],
  },
  {
    id: "core-bindings",
    name: "Universal Module Bindings",
    description: "Core-owned binding layer that inventories all known modules before routing, proxying, importing, or executing anything.",
    sourcePath: "services/grav-core/src/module-bindings.ts, services/grav-core/src/core-defense-modules.ts, services/grav-core/src/channels-module.ts, services/grav-core/src/gateway-module.ts, services/grav-core/src/voice-module.ts, services/grav-core/src/adapters",
    connectionState: "connected",
    capabilities: [
      { id: "modules.inventory", title: "Inventory all modules", description: "Inspect every known module source path for manifests, route files, route hints, CLI entrypoints, tool files, config, docs, service envs, and dangerous actions.", status: "connected" },
      { id: "modules.search", title: "Search all modules", description: "Search all known module source trees without executing code or modifying files.", status: "connected" },
      { id: "modules.read", title: "Read module file", description: "Safely read small text/code files from known module source paths only. Path escapes and credential-style files are blocked.", status: "connected" },
      { id: "core.module.inventory", title: "Core module inventory", description: "Inspect modules/core specifically for manifests, routes, contracts, configs, docs, and CLI/tooling signals.", status: "connected" },
      { id: "core.module.search", title: "Search core module", description: "Search modules/core only without executing module code.", status: "connected" },
      { id: "core.module.read", title: "Read core module file", description: "Read small text/code files from modules/core only with path and credential-file guards.", status: "connected" },
    ],
  },
  {
    id: "memory",
    name: "MemPalace Memory",
    description: "Memory, retrieval, and indexing module owned under modules/memory.",
    sourcePath: "modules/memory/mempalace",
    connectionState: "connected",
    capabilities: [
      { id: "memory.search", title: "Search MemPalace", description: "Search modules/memory through mempalace.searcher.search_memories.", status: "connected" },
      { id: "memory.inject", title: "Inject memory into chat", description: "Core uses MemPalace search results as context before provider execution.", status: "connected" },
      { id: "memory.mine", title: "Mine memory", description: "MemPalace CLI remains the ingestion path for mining projects and conversations.", status: "registered" },
    ],
  },
  {
    id: "coding",
    name: "Coding",
    description: "Repository and coding capability contract across OpenHands, Aider, and Claw modules.",
    sourcePath: "modules/coding-openhands, modules/coding-aider, modules/coding-claw, services/grav-core/src/coding-execution.ts",
    connectionState: "connected",
    capabilities: [
      { id: "coding.scan", title: "Repository scan", description: "Guarded local repository inventory for routes, commands, fetch callers, and module entries.", status: "connected" },
      { id: "coding.modules.inventory", title: "Coding module inventory", description: "Inventories the real OpenHands, Aider, and Claw module source trees for manifests, CLI entrypoints, routes, tools, and HTTP clients.", status: "connected" },
      { id: "coding.modules.search", title: "Search coding modules", description: "Searches the real coding module source trees without executing code or modifying files.", status: "connected" },
      { id: "coding.modules.read", title: "Read coding module file", description: "Reads small text/code files from coding modules only; credential-style files and workspace escape paths are blocked.", status: "connected" },
      { id: "coding.execution.contracts", title: "Coding execution contracts", description: "Reports reviewed execution contracts, env gates, source verification, supported actions, and safety policy for coding modules.", status: "connected" },
      { id: "coding.openhands.run", title: "OpenHands execution", description: "Approval-gated service proxy through GRAVITY_OPENHANDS_BASE_URL. It allows only reviewed OpenHands route prefixes and never starts OpenHands itself.", status: "registered" },
      { id: "coding.aider.run", title: "Aider dry-run execution", description: "Approval-gated dry-run through the real modules/coding-aider CLI contract when GRAVITY_ENABLE_CODING_EXECUTION=true. Write/edit mode is not enabled.", status: "registered" },
      { id: "coding.claw.run", title: "Claw execution", description: "Dangerous tool is registered for approval workflow continuity, but execution returns 404 when modules/coding-claw is missing or 501 when present but unreviewed. No Claw CLI/API is treated as connected yet.", status: "missing" },
    ],
  },
  {
    id: "defense",
    name: "Defense",
    description: "Defensive security and local audit capability contract.",
    sourcePath: "modules/defense, services/grav-core/src/core-defense-modules.ts",
    connectionState: "connected",
    capabilities: [
      { id: "defense.inventory", title: "Defense module inventory", description: "Inspect modules/defense specifically for manifests, routes, scanners, policy/config files, docs, and CLI/tooling signals.", status: "connected" },
      { id: "defense.search", title: "Search defense module", description: "Search modules/defense only without executing module code.", status: "connected" },
      { id: "defense.read", title: "Read defense module file", description: "Read small text/code files from modules/defense only with path and credential-file guards.", status: "connected" },
      { id: "defense.scan", title: "Workspace defensive scan", description: "Guarded local checks for secret-like assignments, TODO markers, and large skipped files across the configured workspace.", status: "connected" },
      { id: "defense.module.scan", title: "Defense module scan", description: "Guarded defensive scan filtered to modules/defense findings only.", status: "connected" },
    ],
  },
  {
    id: "voice",
    name: "Voice",
    description: "Realtime voice session, text-to-speech, and speech-to-text module contract.",
    sourcePath: "modules/voice, services/grav-core/src/voice-module.ts, services/grav-core/src/adapters/voice-adapter.ts",
    connectionState: "registered",
    capabilities: [
      { id: "voice.inventory", title: "Voice inventory", description: "Inspect voice module source and probe configured voice service routes with partitioned session/TTS/STT contracts.", status: "connected" },
      { id: "voice.contract", title: "Voice reviewed contract", description: "Return the reviewed voice contract, source inventory, env status, session path prefixes, TTS path prefixes, STT path prefixes, and safety policy.", status: "connected" },
      { id: "voice.search", title: "Search voice module", description: "Search modules/voice only without executing module code.", status: "connected" },
      { id: "voice.read", title: "Read voice module file", description: "Read small text/code files from modules/voice only with path and credential-file guards.", status: "connected" },
      { id: "voice.session", title: "Voice session", description: "Proxy or create realtime sessions when GRAVITY_VOICE_BASE_URL is configured. Only reviewed session paths are allowed: /session and /sessions.", status: "registered" },
      { id: "voice.tts", title: "Voice TTS", description: "Proxy text-to-speech through the configured voice module service. Only reviewed TTS paths are allowed: /tts.", status: "registered" },
      { id: "voice.stt", title: "Voice STT", description: "Proxy speech-to-text through the configured voice module service. Only reviewed STT paths are allowed: /stt.", status: "registered" },
    ],
  },
  {
    id: "channels",
    name: "Channels",
    description: "External channel service adapter contract.",
    sourcePath: "modules/channels, services/grav-core/src/channels-module.ts, services/grav-core/src/adapters/channels-adapter.ts",
    connectionState: "registered",
    capabilities: [
      { id: "channels.inventory", title: "Channels inventory", description: "Inspect channels module source and probe configured channels service routes with partitioned read/send contracts.", status: "connected" },
      { id: "channels.contract", title: "Channels reviewed contract", description: "Return the reviewed channels contract, source inventory, env status, read path prefixes, send path prefixes, and safety policy.", status: "connected" },
      { id: "channels.search", title: "Search channels module", description: "Search modules/channels only without executing module code.", status: "connected" },
      { id: "channels.read", title: "Read channels module file", description: "Read small text/code files from modules/channels only with path and credential-file guards.", status: "connected" },
      { id: "channels.inbox", title: "Channel inbox", description: "Proxy inbox reads to GRAVITY_CHANNELS_BASE_URL when configured. This tool forces GET semantics and only allows reviewed read paths: /health, /status, /providers, /plugins, and /inbox.", status: "registered" },
      { id: "channels.send", title: "Channel send", description: "Proxy outbound channel send calls after operator approval. Only reviewed send paths are allowed: /send and /webhook.", status: "registered" },
    ],
  },
  {
    id: "gateway",
    name: "Gateway",
    description: "Gateway and traffic-control module contract.",
    sourcePath: "modules/gateway, services/grav-core/src/gateway-module.ts, services/grav-core/src/adapters/gateway-adapter.ts",
    connectionState: "registered",
    capabilities: [
      { id: "gateway.inventory", title: "Gateway inventory", description: "Inspect gateway module source and probe configured gateway service routes.", status: "connected" },
      { id: "gateway.contract", title: "Gateway reviewed contract", description: "Return the reviewed gateway contract, source inventory, env status, and currently allowed proxy path prefixes.", status: "connected" },
      { id: "gateway.search", title: "Search gateway module", description: "Search modules/gateway only without executing module code.", status: "connected" },
      { id: "gateway.read", title: "Read gateway module file", description: "Read small text/code files from modules/gateway only with path and credential-file guards.", status: "connected" },
      { id: "gateway.status", title: "Gateway status", description: "Read configured gateway service status through reviewed /status path when GRAVITY_GATEWAY_BASE_URL is configured.", status: "registered" },
      { id: "gateway.proxy", title: "Gateway proxy", description: "Proxy configured gateway calls after operator approval. Allowed prefixes are limited to /health, /status, /routes, and /proxy until a wider route contract is verified.", status: "registered" },
    ],
  },
  {
    id: "orchestration",
    name: "Orchestration",
    description: "Agent and workflow orchestration capability contract.",
    sourcePath: "modules/orchestration, services/grav-core/src/adapters/orchestration-adapter.ts",
    connectionState: "registered",
    capabilities: [
      { id: "orchestration.inventory", title: "Orchestration inventory", description: "Inspect orchestration source and probe configured agent/workflow routes.", status: "connected" },
      { id: "orchestration.workflow.run", title: "Run workflow", description: "Dispatch workflows to the configured orchestration service after operator approval.", status: "registered" },
    ],
  },
  {
    id: "ollama",
    name: "Ollama",
    description: "Local LLM provider contract and optional modules/ollama source binding.",
    sourcePath: "modules/ollama, services/grav-core/src/adapters/ollama-adapter.ts",
    connectionState: "registered",
    capabilities: [
      { id: "ollama.inventory", title: "Ollama inventory", description: "Inspect modules/ollama if present and probe OLLAMA_BASE_URL.", status: "connected" },
      { id: "ollama.models", title: "Ollama models", description: "List models through OLLAMA_BASE_URL /api/tags.", status: "registered" },
      { id: "ollama.generate", title: "Ollama generate", description: "Proxy generate requests through OLLAMA_BASE_URL /api/generate.", status: "registered" },
      { id: "ollama.chat", title: "Ollama chat", description: "Proxy chat requests through OLLAMA_BASE_URL /api/chat.", status: "registered" },
    ],
  },
]

export const gravCoreProviders: GravityModelProvider[] = [
  {
    id: "ollama.local",
    name: "Ollama Local",
    kind: "local",
    statusEndpoint: "/providers",
  },
]

export function getGravCoreStatus(mode: GravityCoreStatus["mode"] = "standalone"): GravityCoreStatus {
  return {
    ok: true,
    service: "grav-core",
    version: "0.0.1",
    timestamp: new Date().toISOString(),
    mode,
    modules: gravCoreModules,
    providers: gravCoreProviders,
    endpoints: {
      status: "/status",
      health: "/health",
      modules: "/modules",
      providers: "/providers",
      skills: "/skills",
      tools: "/tools",
      runTool: "/tools/run",
      chat: "/chat",
      audit: "/audit",
      memorySearch: "/memory/search",
    },
  }
}
