export const gravityEndpoints = {
  assistant: {
    status: "/api/assistant/status",
    chat: "/api/assistant/chat",
  },
  core: {
    status: "/api/core/status",
    skills: "/api/core/skills",
    tools: "/api/core/tools",
    runTool: "/api/core/tools/run",
    audit: "/api/core/audit",
    approvals: "/api/core/approvals",
    approvalApprove: (id: string) => `/api/core/approvals/${encodeURIComponent(id)}/approve`,
    approvalExecute: (id: string) => `/api/core/approvals/${encodeURIComponent(id)}/execute`,
    approvalReject: (id: string) => `/api/core/approvals/${encodeURIComponent(id)}/reject`,
  },
  runtime: {
    ollamaStatus: "/api/ollama/status",
    ollamaChat: "/api/ollama/chat",
  },
  modules: {
    allStatus: "/api/modules/status",
    coreStatus: "/api/core/status",
    memoryStatus: "/api/memory/status",
    channelsStatus: "/api/channels/status",
    voiceStatus: "/api/voice/status",
    codingStatus: "/api/coding/status",
    defenseStatus: "/api/defense/status",
    gatewayStatus: "/api/gateway/status",
  },
  actions: {
    memorySearch: "/api/memory/search",
    memorySave: "/api/memory/save",
    memoryForget: "/api/memory/forget",
    codingScan: "/api/coding/scan",
    defenseScan: "/api/defense/scan",
    voiceSession: "/api/voice/session",
    channelsInbox: "/api/channels/inbox",
  },
  planned: {
    gatewayProxy: "/api/gateway/proxy",
    codingEdit: "/api/coding/edit",
    codingRun: "/api/coding/run",
    defenseReport: "/api/defense/report",
    channelsSend: "/api/channels/send",
  },
} as const