mode: api_gateway

server:
  bind_address: "0.0.0.0:8484"
  workers: 4

logging:
  level: info

upstreams:
  users_server:
    servers:
      - "127.0.0.1:3001"   # json-server --port 3001 db-users.json
    strategy: round_robin
    tls: false

  products_server:
    servers:
      - "127.0.0.1:3002"   # json-server --port 3002 db-products.json
    strategy: round_robin
    tls: false

  web_server:
    servers:
      - "127.0.0.1:3003"   # json-server --port 3003 db-web.json
    strategy: round_robin
    tls: false

api_gateway:
  routes:
    users_api:
      path_pattern: "^/users"
      methods: [GET, POST, PUT, DELETE]
      upstream: users_server
      strip_prefix: false
      middlewares: []

    products_api:
      path_pattern: "^/products"
      methods: [GET, POST, PUT, DELETE]
      upstream: products_server
      strip_prefix: false
      middlewares: []

    web_app:
      path_pattern: "^/"
      methods: [GET, POST]
      upstream: web_server
      strip_prefix: false
      middlewares: []

  middlewares: {}

control_api:
  enabled: true
  bind_address: "0.0.0.0:8485"
  api_key: "admin-key-12345"
